
version: "3"


services:
  server:
    build: server/

    command: python ./server.py

    ports:
      - 3000:3000

  client:
    build: client/

    command: python ./client.py

    network_mode: host

    depends_on:
      - server
      
    environment:
    # error: could not connect to display
      - DISPLAY=host.docker.internal:0